### ISSUE TITLE
Help text is longer than 25 lines

### ISSUE THREAD

**Issue by dpgeorge** [bbcmicrobit/micropython#21]
We want the help text to be minimal and fit on a small terminal screen (eg 25 lines).

We can shorten the current help text and provide pointers to further places to look for help.

One way of doing this is allow the user to type `help('some_topic')` and then it prints specific help for that topic.  The main help would tell you what topics are available.  This is how CPython works.

Eg we could have `help('modules')` to list available modules (same as CPython).  And `help('demo')` to list some quick demo scripts.

**Comment by willingc** [comment]
I have started to work on this issue in my fork of this repo.

My initial approach is to break up the long initial welcome message into smaller messages that could be combined as desired later. I will begin working from @dpgeorge's approach of ``help('some_topic')``.

**Comment by willingc** [comment]
@dpgeorge @ntoll @markshannon I want to clarify some semantics when it comes to the words 'screen' and 'display' since the words pop up in the API, examples, and issues. My current understanding, and please do correct me, is that typically people refer to:

display => the LED grid on the microbit
screen => the higher level term for content on the LED grid on the microbit
terminal screen => an external monitor or output display; info is sent from microbit via serial connection or BLE to an external display/mobile device/computer

It's pretty easy in docs, comments, and conversations to use 'screen' and 'display' interchangeably. From the API perspective, is 'display' limited to the hardware LED grid on the microbit? Where 'screen' is informally used to refer to any visual output device?

**Comment by larryhastings** [comment]
Personally I haven't been consistent about this, and your comment suggests to me that we should definitely be consistent.

Do you think we need this conceptual distinction between "display" and "screen"?  My suspicion is, no.  We should have one term, for the 5x5 LED matrix, and I nominate "display" as superior to "screen" here.

A side note: is MicroPython on the micro:bit going to permit use of BLE?  If not, we probably shouldn't bother to mention it (except to say that it isn't supported).  Also, I hadn't realized BLE allowed connecting up a "display" like that.  Does it permit a REPL?  Is it conceptually a serial device, or something else?

**Comment by sparkslabs** [comment]
Hi,


For the microbit - I've always used the term 5x5 LED Display - from the
original implementation and the reference specification docs (display
management etc) so definitely display. Before that in the original
requirements we always described it as a display.

Content displayed on the display is an Image.

(These are concepts which are valid and used across all the interfaces, and
should be consistent across those IMO - otherwise we're being different for
the sake of being different)

The REPL over USB serial I'd view as a terminal screen, and if it becomes
available over bluetooth, again I'd view as a terminal screen. However,
that strikes me as more of a micropython thing rather than a microbit thing
(IYSWIM), so whatever the norm is for micropython then I'd expect to take
precedence. (If it gets discussed there)


Michael.

**Comment by willingc** [comment]
@sparkslabs Thanks. That helps clarify for me.

**Comment by ntoll** [comment]
#97 is related to this.

**Comment by ntoll** [comment]
Fixed by  #97
