### ISSUE TITLE
Create radio module based on DAL implementation

### ISSUE THREAD

**Issue by ntoll** [bbcmicrobit/micropython#245]
What the title says. This should be a separate module so the radio feature is not automatically available to kids (they have to explicitly import it).

**Comment by damianburrin** [comment]
What us the concern @ntoll ?

**Comment by ntoll** [comment]
The BBC have a concern surrounding child protection. I believe this shouldn't stop us implementing this feature since I believe it spurious.h

**Comment by damianburrin** [comment]
>The BBC have a concern surrounding child protection
Oh ok.  Seems a bit over the top to me. You'd need to have a program instalked to recieve any form of message and then from fairly close. 
I hope to be able to use this feature in python rather than C.  Ive got a neat idea of a classroom 'Exit Pass' 
On 22 May 2016 19:45, Nicholas Tollervey <notifications@github.com> wrote:The BBC have a concern surrounding child protection. I believe this shouldn't stop us implementing this feature since I believe it spurious.h

**Comment by ntoll** [comment]
Exactly... OTT.

It's coming.

**Comment by markshannon** [comment]
We have a radio module now.
