### ISSUE TITLE
Add a music module

### ISSUE THREAD

**Issue by ntoll** [bbcmicrobit/micropython#31]
It should be possible to make sweet music using MicroPython on the micro:bit.

To this end there should be a `music` namespace containing the simplest yet most helpful functions needed to make this work. 

Furthermore, we'll need to define an easy-to-understand DSL for kids and teachers to use for specifying notes.

Finally, it would be wonderful if such interactions could be optionally allowed to run in the background (in a similar way to the `display.animate` method).

**Comment by matthewelse** [comment]
Just realised - I almost forgot about the async work for this module - I'm going to try and have a look at this in the next week I think.

**Comment by ntoll** [comment]
Great stuff! :-)

**Comment by dpgeorge** [comment]
@matthewelse any update on async music?  One should be able to put a simple hook in main.cpp:ticker() to schedule the next note.

**Comment by matthewelse** [comment]
@dpgeorge I've been quite busy with uni work over the last few weeks unfortunately - I actually made quite a bit of progress with it before I forgot about it for a while, so I might go back and have a look at it once I've finished off the stuff I have to do at the moment. Hopefully I should have some free time tomorrow, depending on how things go.

**Comment by dpgeorge** [comment]
@matthewelse ok.  If you just want to post what you already have and let someone else take it up, that would be fine.

**Comment by ntoll** [comment]
@matthewelse how's this going..? :-)

**Comment by dpgeorge** [comment]
I am now working on async music.

**Comment by dpgeorge** [comment]
Async music implemented in 0189136af557bc2c8514935f7351bcaafe32c47f

Remind me again why it's a music object within the microbit module, and not a music module in its own right?

**Comment by ntoll** [comment]
@dpgeorge I don't remember any reason why it's in the microbit module. To be honest I'm not sure it should be since the microbit module is all about access to the device itself. A music module is something that builds on top of that.

I'm in a long train journey to Birmingham late this afternoon. I'll have a play with this code while on the journey. ;-)

**Comment by matthewelse** [comment]
Thanks @dpgeorge - sorry about that I haven't had much time to look at this unfortunately.

**Comment by dpgeorge** [comment]
@matthewelse no problem :)

I think we should make it a separate music module.  Now that I revisited this code after a few weeks not using it, my first instinct was that I should do "import music", and then I was a bit surprised to see that music was a singleton object within microbit module.

If we have a neopixel driver in a neopixel module, then it makes sense that music is a separate module as well.  Music is slightly advanced because it requires you to attach a speaker to pins, so doing "import music" is not going to be a hurdle.

**Comment by dpgeorge** [comment]
I made "music" a module in a9ccc4812d23829898915b9b92ea56d756517f35.  You now need to import it before using it (import music).

The title of this issue is anyway "add music *module*", and in fact the docs that have been written assumed that music was a module, so I think it's clear that it should indeed be a module :)

**Comment by dpgeorge** [comment]
There may be things to tweak, bugs to fix and more tunes to add, but I think we can close this issue for now because we do indeed have a very nice music module.
