### ISSUE TITLE
set_pull AttributeError

### ISSUE THREAD

**Issue by DavidWhaleMEF** [bbcmicrobit/micropython#463]
set_pull as documented in the published docs, does not work...

http://microbit-micropython.readthedocs.io/en/latest/pin.html?highlight=set_pull

![screen shot 2017-08-24 at 10 06 47](https://user-images.githubusercontent.com/25079586/29658775-08e5e9b6-88b4-11e7-8886-bf19be5e6341.png)

![screen shot 2017-08-24 at 10 08 08](https://user-images.githubusercontent.com/25079586/29658802-276ecfce-88b4-11e7-84d4-a8262ae88e8c.png)

Mu version 0.9.13

**Comment by DavidWhaleMEF** [comment]
FYI @jaustin @carlosperate @ntoll any comments? What is the URL to the correct version of the MicroPython docs for the current latest Mu 0.9.13 and for the version deployed at python.microbit.org (i.e. where the docs match the deployed codebase)? Thanks!

**Comment by carlosperate** [comment]
There is no URL as Read The Docs has only got the "latest" version building from master.

Tracking back a little we have Mu last updated uFlash in https://github.com/mu-editor/mu/commit/39876bfad8775d685b95632583997adde3b40b16 and uFlash updated the hex file in https://github.com/ntoll/uflash/commit/fe26fe8ea0b7943674cb8165e6939cba3ef0dc88 on the 23rd of October 2016. Assuming it was a build from master, then we are looking at https://github.com/bbcmicrobit/micropython/commit/525d88c73f2b81d319efa3889cf5424ebfdc1770 .

If we create a tag to that commit (0.9 is the original micro:bit march release, so 0.10? 0.9.13 to correlate with Mu?), it looks like Read The Docs could pick it up? I'm not entirely sure: http://docs.readthedocs.io/en/latest/versions.html#how-we-envision-versions-working
Otherwise we have a branch already for 0.9, we could make one for this version as well.

I think @deshipu has some experience configuring these types of docs as well, so it'd be great to get your input.

For reference, we have these issues discussing versioning: https://github.com/bbcmicrobit/micropython/issues/370 and https://github.com/bbcmicrobit/micropython/issues/199

**Comment by deshipu** [comment]
We can enable any of the tags or branches to be build by readthedocs,
and we can also make any of them the default. They will appear in the
menu in the bottom left corner, where the green "v: latest" is, and you
can switch between them (or link to them).

**Comment by carlosperate** [comment]
Thanks @deshipu, that's great. Can all that be done from within the Read the docs panel? Ideally that'd be the best way as to avoid having to change any of the files in the repository.

**Comment by deshipu** [comment]
Yes, see https://readthedocs.org/dashboard/microbit-micropython/versions/

**Comment by carlosperate** [comment]
I think only owners have access to that page (I get a 404), but it sounds like the easiest way forward is to create a branch with the "new" version name for https://github.com/bbcmicrobit/micropython/commit/525d88c73f2b81d319efa3889cf5424ebfdc1770 and then add it as a version in Read The Docs.

**Comment by carlosperate** [comment]
Btw, what branch/commit is the "stable" version of the docs based on?

**Comment by deshipu** [comment]
Hmm, there is no such branch in the repository now, but maybe there used to be?

**Comment by carlosperate** [comment]
Based on http://docs.readthedocs.io/en/latest/versions.html it's probably meant to point to the last tag, probably the same as 0.9 now?

**Comment by DavidWhaleMEF** [comment]
@ntoll FYI re: https://twitter.com/Vlastimil_Hovan/status/940884073446367233

**Comment by DavidWhaleMEF** [comment]
@carlosperate is it possible to fix this do you know (get the docs in line with the currently deployed version of MicroPython in mu 0.9.13 and python.microbit.org) - I often see people bumping into this particular issue with set_pull, and I don't know what other aspects of the docs are out of step with reality to know if people are struggling with other things.

**Comment by carlosperate** [comment]
It looks like we already have `v0.9` of the docs: http://microbit-micropython.readthedocs.io/en/0.9/

We should probably set it as the default for http://microbit-micropython.readthedocs.io instead of `latest`, until v1.0 is released. I don't have access to this project, so cannot see what commit does `0.9` points to, or change any of the settings. @ntoll or @deshipu would be able to do that.

**Comment by deshipu** [comment]
I just changed the default to be 0.9.

**Comment by carlosperate** [comment]
Thanks @deshipu!

**Comment by DavidWhaleMEF** [comment]
Thanks @deshipu and @carlosperate !!

**Comment by DavidWhaleMEF** [comment]
The workaround here (Reported by Vlastimil Hovan on twitter here: https://twitter.com/Vlastimil_Hovan/status/940902464575950848 is...

use analog_read()
and make sure you are aware that all 3 round pins have a weak pull-up fitted on the board.

The technical data sheet is here: http://tech.microbit.org/hardware/edgeconnector_ds/

The weak pullups (used for touch sensing) are 10M pullup (and internally the pins by default will most likely have a 12k on-chip pull-down enabled)

**Comment by microbit-carlos** [comment]
https://github.com/bbcmicrobit/micropython/issues/498 has been created to make sure we have the correct default docs until v1.0 is released.
