### ISSUE TITLE
Necessary to use pip to update cryptopgraphy module...

### ISSUE THREAD

**Issue by RandoSY** [bbcmicrobit/micropython#482]
Building from source in/with both Win32 and Ubuntu 17.10 required ...

**pip install cryptography --upgrade**
Collecting cryptography
  Downloading cryptography-2.1.4-cp27-cp27m-win32.whl (1.1MB)
    100% |################################| 1.1MB 632kB/s

the 2.03 module had issues.

**Comment by carlosperate** [comment]
Looks like this is now included in the Yotta readme as well:
https://github.com/ARMmbed/yotta/pull/828/files

It should be fixed by next realease of Yotta, but taking in consideration there is clear indication of when that might be (last release was 10 months ago), we should keep this opened until that happens.

**Comment by microbit-carlos** [comment]
There has just been a new version of Yotta released (v0.18.5 https://pypi.org/project/yotta/#history) that has fixed this issue.

**Comment by microbit-carlos** [comment]
Been using the latest Yotta for a while and this issue is fixed, so closing this one.
@RandoSY thanks for reporting it, it has certainly been useful to have the solution listed here!
