### ISSUE TITLE
micro:bit version string with/without a 'v'

### ISSUE THREAD

**Issue by carlosperate** [bbcmicrobit/micropython#534]
We used to have the version as a string like:

```
micro:bit v1.0.0-beta.1+8f503af on 2018-7-9; MicroPython v1.9.2-34-gd64154c73 on 2017-09-01
```

And now it's:

```
micro:bit 1.0.0-beta.1+83b66f3-dirty on 2018-07-15; MicroPython v1.9.2-34-gd64154c73 on 2017-09-01
```

We no longer have a v in from of `1.0.0...`.

(In contrast version 0.9 just had the upstream MicroPython version as `v1.7-9-gbe020eb on 2016-04-18', machine='micro:bit with nRF51822`)

Changed was made in this commit https://github.com/bbcmicrobit/micropython/commit/5e1e6bb2475473813916ba8c4c50dcd8c3d3cabd and likely done at the time because the git tag already contained the 'v' in its string.

I'm not 100% sure if the 'v' in the name is completely appropriate for semver. But I think either way works.

@ntoll, do you have any thoughts on this?

**Comment by dpgeorge** [comment]
> Changed was made in this commit 5e1e6bb and likely done at the time because the git tag already contained the 'v' in its string.

Actually, I think that particular commit did not change it, because the git tag did start with a "v".  What changed it was 834df70bffa18a948f2f655840de59aeaeec3a77 which went back to using `RELEASE`.  It was my mistake not to put the "v" back in to retain the same behaviour.

I think the "v" should be put back in.
